### ISSUE TITLE
`reset` command will not delete command log before reset

### ISSUE THREAD

**Issue by JasonMo1** [Zeal8bit/Zeal-8-bit-OS#10] opened 2023-08-25 04:24 UTC
The reproduction method is in this gif：
![bug.gif](https://github.com/Zeal8bit/Zeal-8-bit-OS/assets/111677135/73ab3307-911b-4fb6-9b4d-f74d1c4ff53e)

**Comment by Zeal8bit** [comment] 2023-12-20 09:34
Thanks for reporting!
I was able to reproduce part of it on the latest `master`: the characters types would be shown, but the character under the cursor would be the same as in the previous run.
This is surely due to the fact that the screen is not completely erased on startup, the driver can do this. I will investigate on that

**Comment by Zeal8bit** [comment] 2024-07-08 03:43
This is now fixed, closing

**Closed by Zeal8bit** 2024-07-08 03:43 UTC
